export const popularProducts = [
    {
        id: 1,
        image: 'apple',
        title: 'Green Apple',
        price: 14.99,
        oldPrice: 20.99,
        discount: 50,
        rating: 4,
    },
    {
        id: 2,
        image: 'orange',
        title: 'Fresh Indian Malta',
        price: 20.00,
        oldPrice: null,
        discount: null,
        rating: 4,
    },
    {
        id: 3,
        image: 'cabbage',
        title: 'Chinese cabbage',
        price: 12.00,
        oldPrice: null,
        discount: null,
        rating: 4,
    },
    {
        id: 4,
        image: 'lettuce',
        title: 'Green Lettuce',
        price: 9.00,
        oldPrice: null,
        discount: null,
        rating: 4,
    },
    {
        id: 5,
        image: 'eggplant',
        title: 'Eggplant',
        price: 34.00,
        oldPrice: null,
        discount: null,
        rating: 4,
    },
    {
        id: 6,
        image: 'potatoes',
        title: 'Big Potatoes',
        price: 20.00,
        oldPrice: null,
        discount: null,
        rating: 4,
    },
    {
        id: 7,
        image: 'corn',
        title: 'Corn',
        price: 20.00,
        oldPrice: null,
        discount: null,
        rating: 4,
    },
    {
        id: 8,
        image: 'cauliflower',
        title: 'Fresh Cauliflower',
        price: 12.00,
        oldPrice: null,
        discount: null,
        rating: 4,
    },
    {
        id: 9,
        image: 'capsicum',
        title: 'Green Capsicum',
        price: 9.00,
        oldPrice: 20.99,
        discount: null,
        rating: 4,
    },
    {
        id: 10,
        image: 'chili',
        title: 'Green Chili',
        price: 34.00,
        oldPrice: null,
        discount: null,
        rating: 4,
    },
];
